<?php

namespace Database\Seeders;

use App\Models\PageSection;
use Illuminate\Database\Seeder;

class PageSectionSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $sections = [
            // ==================== BERANDA (HOME) ====================
            [
                'page_slug' => 'home',
                'section_key' => 'hero',
                'section_name' => 'Hero Banner Utama',
                'title' => 'Menghidupkan Ruang Belajar Nyata di Balik Kehangatan Desa Nusantara',
                'subtitle' => 'Menjembatani kurikulum institusi pendidikan dengan kearifan tapak, ekologi lokal, dan narasi hidup masyarakat adat di seluruh penjuru Indonesia.',
                'badge' => 'Tahun Akademik ' . date('Y') . '/' . (date('Y') + 1),
                'content' => null,
                'image' => 'assets/img/hd/hero-home.jpg',
                'image_caption' => 'Dokumentasi tapak lapangan aktif tahun akademik ' . date('Y') . '/' . (date('Y') + 1),
                'button_text' => 'Jelajahi Destinasi',
                'button_link' => '/destinasi',
                'secondary_button_text' => null,
                'secondary_button_link' => null,
                'items' => null,
                'order' => 1,
                'is_active' => true,
            ],
            [
                'page_slug' => 'home',
                'section_key' => 'intro_story',
                'section_name' => 'Cerita Pembuka (Asimetris)',
                'title' => 'Desa Bukan Sekadar Destinasi Singgah, Melainkan Buku Pengetahuan yang Terbuka',
                'subtitle' => 'Selama ini, studi lapangan kerap terjebak menjadi ekskursi permukaan. Destinara hadir untuk mengubah cara institusi pendidikan memandang ruang perdesaan.',
                'badge' => 'Arsip Lapangan No. 042',
                'content' => "Kami merancang program pembelajaran berbasis tapak di mana setiap sesi observasi, wawancara mendalam, dan kerja komunal didasarkan pada persetujuan setara dengan pemangku adat setempat.\n\nPeserta tidak hanya membaca teori di ruang ber-AC, melainkan duduk melingkar di serambi rumah warga, mendengarkan siklus musim langsung dari petani penjaga benih, dan memahami dinamika sosio-ekologis secara utuh.",
                'image' => 'assets/img/hd/story-sikka.jpg',
                'image_caption' => 'Tapak Studi Etnobotani Pewarnaan Alami, Sanggar Tarum, Kulon Progo',
                'button_text' => 'Pelajari Pendekatan Kami',
                'button_link' => '/tentang-kami',
                'secondary_button_text' => null,
                'secondary_button_link' => null,
                'items' => null,
                'order' => 2,
                'is_active' => true,
            ],
            [
                'page_slug' => 'home',
                'section_key' => 'cta_home',
                'section_name' => 'Banner Ajakan Kemitraan (CTA)',
                'title' => 'Siap Merancang Pembelajaran Lapangan yang Mengakar?',
                'subtitle' => 'Konsultasikan kebutuhan kurikulum sekolah, topik riset kampus, atau penjajakan kemitraan desa Anda bersama fasilitator Destinara.',
                'badge' => 'Pintu Kemitraan Terbuka',
                'content' => null,
                'image' => null,
                'image_caption' => null,
                'button_text' => 'Konsultasi Kemitraan',
                'button_link' => '/kontak',
                'secondary_button_text' => 'Unduh Panduan Kemitraan',
                'secondary_button_link' => '/untuk-sekolah',
                'items' => null,
                'order' => 3,
                'is_active' => true,
            ],

            // ==================== TENTANG KAMI ====================
            [
                'page_slug' => 'about',
                'section_key' => 'hero',
                'section_name' => 'Hero Banner Tentang Kami',
                'title' => 'Tentang Kami: Merajut Dialog Setara antara Ruang Kuliah dan Kearifan Warga Tapak Nusantara',
                'subtitle' => 'Didokumentasikan sejak 2018 sebagai inisiatif perintis pendidikan lapangan berbasis etika tapak di Indonesia.',
                'badge' => 'Catatan Pendirian & Nilai Dasar',
                'content' => null,
                'image' => 'assets/img/hd/hero-about.jpg',
                'image_caption' => 'Arsip Inisiatif Destinara — Yogyakarta, Magelang, & Enrekang',
                'button_text' => null,
                'button_link' => null,
                'secondary_button_text' => null,
                'secondary_button_link' => null,
                'items' => null,
                'order' => 1,
                'is_active' => true,
            ],
            [
                'page_slug' => 'about',
                'section_key' => 'manifesto',
                'section_name' => 'Manifesto Filosofi & Mikro Metrik',
                'title' => '“Pendidikan tidak semestinya datang ke desa sebagai penilai luar, melainkan sebagai tamu yang beradab dan pembelajar yang rendah hati.”',
                'subtitle' => 'Sebuah pegangan moral yang kami tuangkan dalam setiap penyusunan protokol etika tapak, modul pembekalan siswa, dan interaksi dengan sesepuh adat.',
                'badge' => 'Filosofi Dasar',
                'content' => null,
                'image' => null,
                'image_caption' => null,
                'button_text' => null,
                'button_link' => null,
                'secondary_button_text' => null,
                'secondary_button_link' => null,
                'items' => [
                    ['stat' => '12 Orang', 'label' => 'Kapasitas Kelompok', 'desc' => 'Batas ketat daya tampung per kelompok guna menekan beban ekologis tapak.'],
                    ['stat' => '100% FPIC', 'label' => 'Persetujuan Musyawarah', 'desc' => 'Persetujuan awal tanpa paksaan (Free Prior Informed Consent) bersama dewan musyawarah desa mitra.'],
                    ['stat' => '40% Alokasi', 'label' => 'Kedaulatan Finansial', 'desc' => 'Dari biaya program dialirkan langsung ke kas desa mitra dan regenerasi sanggar adat lokal.']
                ],
                'order' => 2,
                'is_active' => true,
            ],
            [
                'page_slug' => 'about',
                'section_key' => 'founder_story',
                'section_name' => 'Kisah Pendiri & Arsip Sejarah',
                'title' => 'Bermula dari Keresahan atas Ekskursi yang Berjarak',
                'subtitle' => 'Catatan perjalanan inisiator dalam menata ulang relasi riset dan komunitas tapak.',
                'badge' => 'Arsip Lapangan Sejak 2018',
                'content' => "Pada musim kemarau 2018, sekelompok peneliti muda berkunjung ke sebuah desa perajin tenun di Flores Barat. Mereka menyaksikan bagaimana puluhan rombongan pelajar datang silih berganti setiap bulan: mengambil foto, menyalin sedikit informasi dari brosur, lalu pergi tanpa menyisakan pertukaran makna yang berarti bagi para tetua penenun.\n\nKesenjangan inilah yang melahirkan Destinara. Kami meyakini bahwa belajar di luar kelas harus menghasilkan penghormatan timbal balik: siswa dan peneliti memperoleh pemahaman kontekstual yang mendalam, sementara desa mitra mendapatkan pengakuan atas kedaulatan pengetahuan lokal mereka.",
                'image' => 'assets/img/hd/about-musyawarah.jpg',
                'image_caption' => 'Musyawarah pembentukan etika tapak bersama dewan tetua adat dan fasilitator Destinara di Enrekang.',
                'button_text' => null,
                'button_link' => null,
                'secondary_button_text' => null,
                'secondary_button_link' => null,
                'items' => null,
                'order' => 3,
                'is_active' => true,
            ],
            [
                'page_slug' => 'about',
                'section_key' => 'values',
                'section_name' => 'Empat Pilar Nilai Dasar',
                'title' => 'Empat Pilar Nilai Pembelajaran Tapak',
                'subtitle' => 'Pedoman yang kami pegang teguh dalam setiap penyusunan modul kurikulum dan pemilihan mitra desa.',
                'badge' => 'Fondasi Etika',
                'content' => null,
                'image' => null,
                'image_caption' => null,
                'button_text' => null,
                'button_link' => null,
                'secondary_button_text' => null,
                'secondary_button_link' => null,
                'items' => [
                    ['icon' => 'handshake', 'title' => 'Kemitraan Setara', 'desc' => 'Warga desa adalah narasumber utama dan rekan dialog, bukan sekadar objek studi atau penyedia jasa akomodasi.'],
                    ['icon' => 'nature', 'title' => 'Batas Ekologis Rendah Jejak', 'desc' => 'Jumlah rombongan dibatasi ketat agar ritme sosial dan kelestarian ekosistem tapak tidak terdistorsi oleh kedatangan kelompok luar.'],
                    ['icon' => 'gavel', 'title' => 'Transparansi & Hak Kepemilikan Data', 'desc' => 'Seluruh data observasi, dokumentasi audio-visual, dan jurnal lapangan disalin kembali dan diarsipkan di balai desa mitra.'],
                    ['icon' => 'savings', 'title' => 'Kedaulatan Ekonomi Lokal', 'desc' => 'Pengeluaran logistik, makan, homestay, dan fasilitasi dialirkan sepenuhnya kepada dapur warga dan kas sanggar komunitas.']
                ],
                'order' => 4,
                'is_active' => true,
            ],
            [
                'page_slug' => 'about',
                'section_key' => 'governance',
                'section_name' => 'Tata Kelola Etika & Standar Lapangan',
                'title' => 'Tata Kelola Etika & Standar Perlindungan Lapangan',
                'subtitle' => 'Kami menerapkan audit risiko berlapis, asuransi kecelakaan lapangan komprehensif, dan rasio pendamping bersertifikasi 1:8 untuk memastikan keselamatan fisik dan psikologis seluruh peserta.',
                'badge' => 'SOP Kepatuhan & Mitigasi',
                'content' => 'Setiap modul dipandu oleh fasilitator lapangan berlatar belakang disiplin ilmu terkait dan relawan lokal. Kami tidak mengizinkan aktivitas yang mengeksploitasi privasi warga atau merusak cagar alam.',
                'image' => 'assets/img/hd/about-jurnal.jpg',
                'image_caption' => 'Jurnal lapangan dan lembar refleksi harian peserta sebagai portofolio akademik resmi.',
                'button_text' => 'Konsultasikan Kemitraan',
                'button_link' => '/kontak',
                'secondary_button_text' => null,
                'secondary_button_link' => null,
                'items' => null,
                'order' => 5,
                'is_active' => true,
            ],

            // ==================== UNTUK SEKOLAH ====================
            [
                'page_slug' => 'for-schools',
                'section_key' => 'hero',
                'section_name' => 'Hero Banner Untuk Sekolah',
                'title' => 'Study tour yang terencana, aman, dan berdokumen resmi',
                'subtitle' => 'Menjawab kepatuhan penuh terhadap regulasi dinas pendidikan serta mengintegrasikan capaian Silabus Kurikulum Merdeka ke dalam ekosistem perdesaan yang autentik.',
                'badge' => 'Program Pembelajaran Luar Kelas & Riset Aplikatif',
                'content' => null,
                'image' => 'assets/img/hd/sekolah-diskusi.jpg',
                'image_caption' => 'Sanggar Lapangan Pentingsari — Observasi etnobotani terpadu Kelas VIII',
                'button_text' => 'Konsultasikan Kunjungan Sekolah',
                'button_link' => '/kontak',
                'secondary_button_text' => null,
                'secondary_button_link' => null,
                'items' => null,
                'order' => 1,
                'is_active' => true,
            ],
            [
                'page_slug' => 'for-schools',
                'section_key' => 'benefits',
                'section_name' => 'Empat Keunggulan Kurikulum Sekolah',
                'title' => 'Mengapa Sekolah Mempercayakan Program Lapangan kepada Destinara?',
                'subtitle' => 'Dirancang khusus untuk membebaskan tim guru dari kerumitan logistik dan risiko kepatuhan dinas.',
                'badge' => 'Standar Institusional',
                'content' => null,
                'image' => null,
                'image_caption' => null,
                'button_text' => null,
                'button_link' => null,
                'secondary_button_text' => null,
                'secondary_button_link' => null,
                'items' => [
                    ['icon' => 'verified_user', 'title' => 'Kepatuhan Regulasi Dinas', 'desc' => 'Kelengkapan administrasi resmi mencakup izin dinas pendidikan, surat rekomendasi wilayah, dan MoU berpayung hukum legal.'],
                    ['icon' => 'menu_book', 'title' => 'Modul Silabus Tematik Terpadu', 'desc' => 'Materi disesuaikan dengan jenjang SMP/SMA: P5 Gaya Hidup Berkelanjutan, Kearifan Lokal, dan Rekayasa Teknologi Sederhana.'],
                    ['icon' => 'health_and_safety', 'title' => 'Protokol Keamanan & Mitigasi Rasio 1:8', 'desc' => 'Setiap 8 siswa didampingi oleh 1 fasilitator bersertifikasi pertolongan pertama (First Aid) dan relawan pemandu tapak desa.'],
                    ['icon' => 'receipt_long', 'title' => 'Laporan Pertanggungjawaban Rapi', 'desc' => 'Format pelaporan keuangan dan capaian belajar siap audit, dilengkapi portofolio lembar kerja refleksi siswa.']
                ],
                'order' => 2,
                'is_active' => true,
            ],
            [
                'page_slug' => 'for-schools',
                'section_key' => 'flow',
                'section_name' => 'Alur Kerjasama Lapangan Sekolah',
                'title' => 'Empat Langkah Kemitraan Menuju Lapangan',
                'subtitle' => 'Alur terstruktur dari penyusunan tema hingga serah terima berkas evaluasi akhir.',
                'badge' => 'Alur Kerja Terstandar',
                'content' => null,
                'image' => null,
                'image_caption' => null,
                'button_text' => null,
                'button_link' => null,
                'secondary_button_text' => null,
                'secondary_button_link' => null,
                'items' => [
                    ['step' => '01', 'title' => 'Pemetaan Silabus & Audiensi Kurikulum', 'desc' => 'Tim kurator kami mendiskusikan capaian pembelajaran yang ditargetkan guru mata pelajaran.'],
                    ['step' => '02', 'title' => 'Penyusunan Rencana Operasional & Perizinan', 'desc' => 'Penerbitan proposal teknis, MoU, dokumen mitigasi risiko rute perjalanan, dan izin desa mitra.'],
                    ['step' => '03', 'title' => 'Pembekalan Peserta & Pelaksanaan Lapangan', 'desc' => 'Sesi briefing etika tapak di sekolah dilanjutkan pendampingan intensif selama 2-4 hari di desa.'],
                    ['step' => '04', 'title' => 'Evaluasi Refleksi & Penyerahan Berkas LPJ', 'desc' => 'Penilaian rubrik portofolio siswa, video dokumentasi kegiatan, dan draf laporan keuangan transparan.']
                ],
                'order' => 3,
                'is_active' => true,
            ],
            [
                'page_slug' => 'for-schools',
                'section_key' => 'cta_schools',
                'section_name' => 'CTA Kemitraan Sekolah',
                'title' => 'Rancang Agenda Pembelajaran Luar Kelas Bersama Kami',
                'subtitle' => 'Unduh contoh modul silabus P5 atau diskusikan kebutuhan tanggal dan lokasi bersama perancang kurikulum Destinara.',
                'badge' => 'Konsultasi Sekolah',
                'content' => null,
                'image' => null,
                'image_caption' => null,
                'button_text' => 'Hubungi Koordinator Sekolah',
                'button_link' => '/kontak',
                'secondary_button_text' => 'Lihat Titik Destinasi',
                'secondary_button_link' => '/destinasi',
                'items' => null,
                'order' => 4,
                'is_active' => true,
            ],

            // ==================== UNTUK PENELITI ====================
            [
                'page_slug' => 'for-researchers',
                'section_key' => 'hero',
                'section_name' => 'Hero Banner Untuk Peneliti',
                'title' => 'Infrastruktur Tapak untuk Peneliti, Dosen, dan Tim Riset Mahasiswa',
                'subtitle' => 'Akses perizinan resmi, jejaring narasumber adat kredibel, homestay layak kerja, dan pendamping lapangan berpengalaman di kantong-kantong pengetahuan lokal Nusantara.',
                'badge' => 'Dukungan Metodologi & Fasilitasi Riset Etnografi',
                'content' => null,
                'image' => 'assets/img/hd/peneliti-wawancara.jpg',
                'image_caption' => 'Wawancara mendalam bersama dewan adat tentang pola pewarisan varietas padi lokal',
                'button_text' => 'Ajukan Permohonan Riset',
                'button_link' => '/kontak',
                'secondary_button_text' => null,
                'secondary_button_link' => null,
                'items' => null,
                'order' => 1,
                'is_active' => true,
            ],
            [
                'page_slug' => 'for-researchers',
                'section_key' => 'ethics',
                'section_name' => 'Protokol Riset & Etika Lapangan',
                'title' => 'Protokol Riset Beretika & Menghormati Hak Komunitas',
                'subtitle' => 'Kami menjamin setiap riset yang difasilitasi mematuhi kaidah ilmiah global dan kedaulatan masyarakat adat.',
                'badge' => 'Prinsip Integritas Ilmiah',
                'content' => null,
                'image' => null,
                'image_caption' => null,
                'button_text' => null,
                'button_link' => null,
                'secondary_button_text' => null,
                'secondary_button_link' => null,
                'items' => [
                    ['icon' => 'verified', 'title' => 'Persetujuan FPIC Penuh', 'desc' => 'Setiap topik wawancara dan pengambilan sampel telah dikonsultasikan dalam musyawarah adat sebelum tim riset tiba.'],
                    ['icon' => 'folder_shared', 'title' => 'Salinan Arsip Kembali ke Desa', 'desc' => 'Hasil publikasi jurnal, skripsi, atau tesis wajib diserahkan satu eksemplar dalam bahasa populer untuk perpustakaan desa.'],
                    ['icon' => 'lock', 'title' => 'Perlindungan Pengetahuan Sakral', 'desc' => 'Kerahasiaan mantra, lokasi situs sakral, atau ramuan herbal tertentu dijaga ketat dari komersialisasi sepihak.']
                ],
                'order' => 2,
                'is_active' => true,
            ],
            [
                'page_slug' => 'for-researchers',
                'section_key' => 'facilities',
                'section_name' => 'Fasilitas & Dukungan Lapangan',
                'title' => 'Fasilitas & Dukungan Lapangan yang Disediakan',
                'subtitle' => 'Dukungan menyeluruh agar peneliti dapat fokus pada pengumpulan data berkualitas.',
                'badge' => 'Infrastruktur Riset',
                'content' => null,
                'image' => null,
                'image_caption' => null,
                'button_text' => null,
                'button_link' => null,
                'secondary_button_text' => null,
                'secondary_button_link' => null,
                'items' => [
                    ['title' => 'Akses Listrik & Meja Kerja Homestay', 'desc' => 'Kamar homestay dilengkapi area kerja tenang, colokan listrik stabil, dan koneksi internet cadangan.'],
                    ['title' => 'Penerjemah Bahasa Daerah Lokal', 'desc' => 'Fasilitator pendamping yang fasih bahasa ibu setempat untuk wawancara mendalam dengan sesepuh adat.'],
                    ['title' => 'Logistik & Izin Wilayah Bakesbangpol', 'desc' => 'Bantuan pengurusan izin penelitian tingkat kabupaten/provinsi dan surat pengantar desa.'],
                    ['title' => 'Transportasi Lapangan 4x4 / Trail', 'desc' => 'Armada penunjang untuk menjangkau tapak-tapak pelosok yang sulit dijangkau kendaraan biasa.']
                ],
                'order' => 3,
                'is_active' => true,
            ],

            // ==================== MITRA DESA ====================
            [
                'page_slug' => 'for-villages',
                'section_key' => 'hero',
                'section_name' => 'Hero Banner Mitra Desa',
                'title' => 'Kemitraan yang Menghormati Otonomi, Tradisi, dan Kemakmuran Warga Desa',
                'subtitle' => 'Destinara bukan pengembang pariwisata massal. Kami adalah mitra kerja desa untuk menghidupkan ekosistem pembelajaran yang menjaga kehormatan tapak dan mendatangkan manfaat nyata.',
                'badge' => 'Inisiatif Kemitraan Desa & Komunitas Berkelanjutan',
                'content' => null,
                'image' => 'assets/img/hd/desa-lurah.jpg',
                'image_caption' => 'Musyawarah tahunan peninjauan dana abadi pendidikan desa bersama perwakilan Destinara',
                'button_text' => 'Daftarkan Desa Sebagai Mitra',
                'button_link' => '/kontak',
                'secondary_button_text' => null,
                'secondary_button_link' => null,
                'items' => null,
                'order' => 1,
                'is_active' => true,
            ],
            [
                'page_slug' => 'for-villages',
                'section_key' => 'village_benefits',
                'section_name' => 'Manfaat Kemitraan Desa',
                'title' => 'Manfaat Nyata bagi Komunitas dan Desa Mitra',
                'subtitle' => 'Model bagi hasil yang adil dan perlindungan ketat terhadap ritme sosial masyarakat desa.',
                'badge' => 'Dampak Berkelanjutan',
                'content' => null,
                'image' => null,
                'image_caption' => null,
                'button_text' => null,
                'button_link' => null,
                'secondary_button_text' => null,
                'secondary_button_link' => null,
                'items' => [
                    ['title' => 'Alokasi Dana Kas & Sanggar Desa', 'desc' => 'Setiap peserta berkontribusi langsung ke kas desa dan kas pemeliharaan rumah adat/sanggar seni lokal.'],
                    ['title' => 'Peluang Ekonomi Dapur Warga', 'desc' => 'Penyediaan konsumsi berbasis bahan pangan lokal yang dimasak bergilir oleh kelompok ibu-ibu PKK.'],
                    ['title' => 'Regenerasi Minat Budaya Generasi Muda', 'desc' => 'Anak-anak muda desa dilatih menjadi fasilitator riset dan pemandu tapak berpenghasilan mandiri.'],
                    ['title' => 'Dokumentasi Digital Warisan Leluhur', 'desc' => 'Buku silsilah, tanaman obat, dan arsip cerita lisan dibantu pembukuan digitalnya secara cuma-cuma.']
                ],
                'order' => 2,
                'is_active' => true,
            ],

            // ==================== KONTAK ====================
            [
                'page_slug' => 'contact',
                'section_key' => 'hero',
                'section_name' => 'Hero Banner Halaman Kontak',
                'title' => 'Hubungi Kami',
                'subtitle' => 'Pintu dialog Destinara terbuka bagi pimpinan sekolah, dosen perancang riset, dan pegiat desa yang hendak merumuskan agenda pembelajaran kontekstual di tapak lokal Nusantara.',
                'badge' => 'Ruang Musyawarah & Konsultasi Terbuka',
                'content' => null,
                'image' => null,
                'image_caption' => null,
                'button_text' => null,
                'button_link' => null,
                'secondary_button_text' => null,
                'secondary_button_link' => null,
                'items' => null,
                'order' => 1,
                'is_active' => true,
            ],
            [
                'page_slug' => 'contact',
                'section_key' => 'office_hours',
                'section_name' => 'Waktu Pelayanan & Kunjungan Sekretariat',
                'title' => 'Waktu Pelayanan & Kunjungan Sekretariat',
                'subtitle' => "Senin – Jumat: 08.30 – 17.00 WIB\nSabtu – Minggu: Pendampingan Lapangan (Pertemuan Sekretariat via Janji Temu)",
                'badge' => 'Jam Operasional',
                'content' => 'Untuk kunjungan langsung ke kantor sekretariat Yogyakarta, harap melakukan konfirmasi minimal H-2 agar tim kurator tidak sedang bertugas di tapak desa.',
                'image' => null,
                'image_caption' => null,
                'button_text' => null,
                'button_link' => null,
                'secondary_button_text' => null,
                'secondary_button_link' => null,
                'items' => null,
                'order' => 2,
                'is_active' => true,
            ],
        ];

        foreach ($sections as $section) {
            PageSection::updateOrCreate(
                [
                    'page_slug' => $section['page_slug'],
                    'section_key' => $section['section_key'],
                ],
                $section
            );
        }
    }
}
